export const roundSummaryParityFixtures = Object.freeze([
  {
    name: '배열 순서·결측·퍼팅·벌타·FIR/GIR·스코어 분포를 함께 계산한다',
    payload: {
      holes: [
        {
          holeNumber: 1, sourceOfficialHole: 18, par: 4, score: 1,
          officialPutts: 2, putts: 9, fir: true, gir: true,
          penaltyStrokes: 1, obCount: 1, penaltyCount: 0,
        },
        { holeNumber: 2, sourceOfficialHole: 17, par: 3, score: 1, fir: true, gir: null },
        { holeNumber: 3, sourceOfficialHole: 16, par: 4, score: 3, putts: 1, fir: false, gir: false },
        { holeNumber: 4, sourceOfficialHole: 15, par: 4, score: 4, putts: 2, fir: null, gir: true },
        {
          holeNumber: 5, sourceOfficialHole: 14, par: 4, score: 5, putts: 3,
          fir: true, gir: false, penaltyStrokes: 2, penaltyCount: 2,
        },
        { holeNumber: 6, sourceOfficialHole: 13, par: 4, score: 6, putts: 0, fir: false, gir: null },
        { holeNumber: 7, sourceOfficialHole: 12, par: 4, score: 7, fir: true, gir: true },
        { holeNumber: 8, sourceOfficialHole: 11, par: 4, score: 8, fir: false, gir: false },
        { holeNumber: 9, sourceOfficialHole: 10, score: 5, putts: 1, fir: true, gir: false },
        { holeNumber: 10, sourceOfficialHole: 1, par: 5, score: 1, fir: false, gir: true },
      ],
    },
    expected: {
      enteredHoles: 10,
      parRecordedHoles: 9,
      missingParHoles: 1,
      totalScore: 41,
      totalPar: 36,
      toPar: 0,
      frontScore: 40,
      backScore: 1,
      frontToPar: 4,
      backToPar: -4,
      parCount: 1,
      bogeyCount: 1,
      doubleBogeyCount: 1,
      triplePlusCount: 2,
      scoreOutcomes: [
        { key: '-4', value: -4, label: '-4', count: 1 },
        { key: '-3', value: -3, label: '알바트로스', count: 1 },
        { key: '-2', value: -2, label: '이글', count: 1 },
        { key: '-1', value: -1, label: '버디', count: 1 },
        { key: '0', value: 0, label: '파', count: 1 },
        { key: '1', value: 1, label: '보기', count: 1 },
        { key: '2', value: 2, label: '더블', count: 1 },
        { key: 'triplePlus', value: 3, label: '트리플+', count: 2 },
      ],
      holeInOneCount: 3,
      totalPutts: 9,
      puttAttempts: 6,
      averagePutts: 1.5,
      onePuttCount: 2,
      twoPuttCount: 2,
      threePlusPuttCount: 1,
      penaltyStrokes: 3,
      obCount: 1,
      penaltyCount: 2,
      firHits: 4,
      firAttempts: 8,
      girHits: 4,
      girAttempts: 8,
    },
  },
  {
    name: '빈 holes는 0과 null을 구분한다',
    payload: { holes: [] },
    expected: {
      enteredHoles: 0,
      parRecordedHoles: 0,
      missingParHoles: 0,
      totalScore: 0,
      totalPar: 0,
      toPar: null,
      frontScore: 0,
      backScore: 0,
      frontToPar: null,
      backToPar: null,
      parCount: 0,
      bogeyCount: 0,
      doubleBogeyCount: 0,
      triplePlusCount: 0,
      scoreOutcomes: [],
      holeInOneCount: 0,
      totalPutts: 0,
      puttAttempts: 0,
      averagePutts: null,
      onePuttCount: 0,
      twoPuttCount: 0,
      threePlusPuttCount: 0,
      penaltyStrokes: 0,
      obCount: 0,
      penaltyCount: 0,
      firHits: 0,
      firAttempts: 0,
      girHits: 0,
      girAttempts: 0,
    },
  },
])
