begin;

create table if not exists public.app_diagnostics (
  id bigint generated by default as identity primary key,
  incident_id uuid not null unique,
  stage text not null check (stage in (
    'oauth',
    'profile_load', 'profile_save',
    'rounds_load', 'rounds_save', 'rounds_delete',
    'club_bag_load', 'club_bag_save',
    'distance_history_load', 'distance_history_save',
    'local_storage_parse', 'remote_hydration_delay', 'remote_retry',
    'account_delete', 'api_call'
  )),
  category text not null check (category in ('offline', 'auth', 'timeout', 'server', 'query', 'network', 'storage', 'unknown')),
  http_status smallint check (http_status between 100 and 599),
  app_version text not null check (app_version ~ '^[A-Za-z0-9._+-]{1,64}$'),
  platform text not null check (platform in ('mobile', 'tablet', 'desktop', 'unknown')),
  online boolean not null,
  first_occurred_at timestamptz not null,
  last_occurred_at timestamptz not null,
  occurrence_count integer not null check (occurrence_count between 1 and 9999),
  recovered_at timestamptz,
  recovery_duration_ms integer check (recovery_duration_ms between 0 and 604800000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (first_occurred_at <= last_occurred_at),
  check ((recovered_at is null and recovery_duration_ms is null) or (recovered_at is not null and recovery_duration_ms is not null))
);

create index if not exists app_diagnostics_open_idx
  on public.app_diagnostics (stage, category, last_occurred_at desc)
  where recovered_at is null;
create index if not exists app_diagnostics_retention_idx
  on public.app_diagnostics (last_occurred_at asc);

alter table public.app_diagnostics enable row level security;

create or replace function public.record_app_diagnostic(
  p_kind text,
  p_incident_id uuid,
  p_stage text,
  p_category text,
  p_http_status smallint,
  p_app_version text,
  p_platform text,
  p_online boolean,
  p_first_occurred_at timestamptz,
  p_last_occurred_at timestamptz,
  p_occurrence_count integer,
  p_recovered_at timestamptz default null,
  p_recovery_duration_ms integer default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_kind = 'failure' then
    insert into public.app_diagnostics (
      incident_id, stage, category, http_status, app_version, platform, online,
      first_occurred_at, last_occurred_at, occurrence_count, recovered_at, recovery_duration_ms
    ) values (
      p_incident_id, p_stage, p_category, p_http_status, p_app_version, p_platform, p_online,
      p_first_occurred_at, p_last_occurred_at, p_occurrence_count, null, null
    )
    on conflict (incident_id) do update set
      http_status = excluded.http_status,
      platform = excluded.platform,
      online = excluded.online,
      first_occurred_at = least(public.app_diagnostics.first_occurred_at, excluded.first_occurred_at),
      last_occurred_at = greatest(public.app_diagnostics.last_occurred_at, excluded.last_occurred_at),
      occurrence_count = greatest(public.app_diagnostics.occurrence_count, excluded.occurrence_count),
      recovered_at = null,
      recovery_duration_ms = null,
      updated_at = now()
    where public.app_diagnostics.stage = excluded.stage
      and public.app_diagnostics.category = excluded.category;
    return true;
  end if;

  if p_kind = 'recovery' then
    update public.app_diagnostics
    set recovered_at = greatest(last_occurred_at, p_recovered_at),
        recovery_duration_ms = p_recovery_duration_ms,
        updated_at = now()
    where incident_id = p_incident_id
      and stage = p_stage
      and category = p_category;
    return found;
  end if;

  raise exception 'Unsupported diagnostic kind';
end;
$$;

create or replace function public.purge_expired_app_diagnostics(
  p_now timestamptz default now()
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.app_diagnostics
  where last_occurred_at < p_now - interval '30 days'
    or (recovered_at is not null and recovered_at < p_now - interval '7 days');
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

revoke all on table public.app_diagnostics from anon, authenticated;
revoke all on function public.record_app_diagnostic(text, uuid, text, text, smallint, text, text, boolean, timestamptz, timestamptz, integer, timestamptz, integer) from public, anon, authenticated;
revoke all on function public.purge_expired_app_diagnostics(timestamptz) from public, anon, authenticated;
grant execute on function public.record_app_diagnostic(text, uuid, text, text, smallint, text, text, boolean, timestamptz, timestamptz, integer, timestamptz, integer) to service_role;
grant execute on function public.purge_expired_app_diagnostics(timestamptz) to service_role;

commit;
