begin;

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  default_tee text not null default '화이트' check (default_tee in ('블랙', '블루', '화이트', '골드', '레드')),
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rounds (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text,
  course_name text not null,
  front_course_name text not null,
  back_course_name text not null,
  tee text not null check (tee in ('블랙', '블루', '화이트', '골드', '레드')),
  distance_unit text not null default 'M' check (distance_unit in ('M', 'YD')),
  played_at_local text,
  status text not null default 'in_progress' check (status in ('in_progress', 'completed')),
  completed_at timestamptz,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists rounds_user_updated_idx on public.rounds(user_id, updated_at desc);
create index if not exists rounds_user_status_idx on public.rounds(user_id, status);

create or replace function public.keep_newest_round_version()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.updated_at < old.updated_at then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists rounds_keep_newest on public.rounds;
create trigger rounds_keep_newest
before update on public.rounds
for each row execute function public.keep_newest_round_version();

create table if not exists public.round_holes (
  round_id text not null references public.rounds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  hole_number smallint not null check (hole_number between 1 and 18),
  official_hole_number smallint,
  par smallint check (par between 3 and 6),
  distance numeric check (distance >= 0),
  score smallint check (score >= 0),
  putts smallint check (putts >= 0),
  payload jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (round_id, hole_number)
);

create index if not exists round_holes_user_idx on public.round_holes(user_id, round_id);

create table if not exists public.round_shots (
  round_id text not null,
  hole_number smallint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  shot_sequence smallint not null check (shot_sequence > 0),
  club text,
  remaining_distance numeric check (remaining_distance >= 0),
  trouble_direction text,
  trouble_type text,
  ob_relief text,
  payload jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (round_id, hole_number, shot_sequence),
  foreign key (round_id, hole_number) references public.round_holes(round_id, hole_number) on delete cascade
);

create index if not exists round_shots_user_idx on public.round_shots(user_id, round_id);

create table if not exists public.user_clubs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.club_distance_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  club_id uuid not null references public.user_clubs(id) on delete cascade,
  distance numeric not null check (distance >= 0),
  distance_unit text not null default 'M' check (distance_unit in ('M', 'YD')),
  source text not null default 'manual',
  recorded_at timestamptz not null default now()
);

create index if not exists club_distance_user_idx on public.club_distance_history(user_id, club_id, recorded_at desc);

create or replace function public.sync_round_children_from_payload()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  delete from public.round_holes where round_id = new.id;

  insert into public.round_holes (
    round_id, user_id, hole_number, official_hole_number, par, distance, score, putts, payload, updated_at
  )
  select
    new.id,
    new.user_id,
    coalesce(nullif(hole.value->>'holeNumber', '')::smallint, hole.ordinality::smallint),
    nullif(hole.value->>'sourceOfficialHole', '')::smallint,
    nullif(hole.value->>'par', '')::smallint,
    nullif(hole.value->>'distance', '')::numeric,
    nullif(hole.value->>'score', '')::smallint,
    nullif(hole.value->>'putts', '')::smallint,
    hole.value,
    new.updated_at
  from jsonb_array_elements(coalesce(new.payload->'holes', '[]'::jsonb)) with ordinality as hole(value, ordinality);

  insert into public.round_shots (
    round_id, hole_number, user_id, shot_sequence, club, remaining_distance,
    trouble_direction, trouble_type, ob_relief, payload, updated_at
  )
  select
    new.id,
    coalesce(nullif(hole.value->>'holeNumber', '')::smallint, hole.ordinality::smallint),
    new.user_id,
    coalesce(nullif(shot.value->>'sequence', '')::smallint, shot.ordinality::smallint),
    nullif(shot.value->>'club', ''),
    nullif(shot.value->>'remainingDistance', '')::numeric,
    nullif(shot.value->>'troubleDirection', ''),
    nullif(shot.value->>'troubleType', ''),
    nullif(shot.value->>'obRelief', ''),
    shot.value,
    new.updated_at
  from jsonb_array_elements(coalesce(new.payload->'holes', '[]'::jsonb)) with ordinality as hole(value, ordinality)
  cross join lateral jsonb_array_elements(coalesce(hole.value->'shots', '[]'::jsonb)) with ordinality as shot(value, ordinality);

  return new;
end;
$$;

drop trigger if exists rounds_sync_children on public.rounds;
create trigger rounds_sync_children
after insert or update of payload on public.rounds
for each row execute function public.sync_round_children_from_payload();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists golf_and_me_on_auth_user_created on auth.users;
create trigger golf_and_me_on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.rounds enable row level security;
alter table public.round_holes enable row level security;
alter table public.round_shots enable row level security;
alter table public.user_clubs enable row level security;
alter table public.club_distance_history enable row level security;

create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "rounds_select_own" on public.rounds for select using (auth.uid() = user_id);
create policy "rounds_insert_own" on public.rounds for insert with check (auth.uid() = user_id);
create policy "rounds_update_own" on public.rounds for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "rounds_delete_own" on public.rounds for delete using (auth.uid() = user_id);

create policy "round_holes_select_own" on public.round_holes for select using (auth.uid() = user_id);
create policy "round_holes_insert_own" on public.round_holes for insert with check (auth.uid() = user_id);
create policy "round_holes_update_own" on public.round_holes for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "round_holes_delete_own" on public.round_holes for delete using (auth.uid() = user_id);

create policy "round_shots_select_own" on public.round_shots for select using (auth.uid() = user_id);
create policy "round_shots_insert_own" on public.round_shots for insert with check (auth.uid() = user_id);
create policy "round_shots_update_own" on public.round_shots for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "round_shots_delete_own" on public.round_shots for delete using (auth.uid() = user_id);

create policy "user_clubs_select_own" on public.user_clubs for select using (auth.uid() = user_id);
create policy "user_clubs_insert_own" on public.user_clubs for insert with check (auth.uid() = user_id);
create policy "user_clubs_update_own" on public.user_clubs for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "user_clubs_delete_own" on public.user_clubs for delete using (auth.uid() = user_id);

create policy "club_distance_select_own" on public.club_distance_history for select using (auth.uid() = user_id);
create policy "club_distance_insert_own" on public.club_distance_history for insert with check (auth.uid() = user_id);
create policy "club_distance_update_own" on public.club_distance_history for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "club_distance_delete_own" on public.club_distance_history for delete using (auth.uid() = user_id);

commit;
